import sys

debugmode='0'
diffdeposit='0'
liquiditycheck='0'
sellpercentcheckbox='0'
sellpricecheckbox='0'
sellsecondscheckbox='0'
buypricecheck='0'
buytokenscheck='0'
selltokenscheck='0'
currency=''
tradeaction=''
tradepair=''
tokenstartprice=''
tokenbuyprice=''
maxslippage='0.99'
diffdepositaddress=''
maxgwei='5'
gaslimit='500000'
tokenethaddress=''
tokenname=''
tokensymbol=''
tokendecimals=''
sellmaxslippage=''
tokensellpercent=''
tokensellseconds=''
tokensellprice=''
ethamounttobuy=''
tokensamounttobuy=''
tokensamounttosell=''
liquidityspeed=''
infuraurl='https://bsc-dataseed1.binance.org'
my_address=''
my_pk=''

sys.path.append(".")
