import sys

debugmode='1'
diffdeposit='0'
liquiditycheck='1'
sellpercentcheckbox='0'
sellpricecheckbox='0'
sellsecondscheckbox='1'
buypricecheck='0'
buytokenscheck='1'
selltokenscheck='0'
forcesellcheck='1'
currency='GBP'
tradeaction='BUY/SELL'
tradepair='WBNB'
tokenstartprice='0'
tokenbuyprice=''
maxslippage='0.01'
diffdepositaddress=''
maxgwei='20'
gaslimit='500000'
tokenethaddress=''
tokenname=''
tokensymbol=''
tokendecimals='18'
sellmaxslippage='0'
tokensellpercent='0'
tokensellseconds='5'
tokensellprice='0'
tokenexactinput='0'
tokenexactoutput='0'
tokensellexactinput='0'
tokensellexactoutput='0'
tokenforcesellpercent='0'
liquidityspeed='0.5'
infuraurl='https://bsc-dataseed1.binance.org'
my_address = ''
my_pk = ''

sys.path.append(".")
